application: proof-of-existence
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "30d"

handlers:
- url: /stylesheets
  static_dir: stylesheets
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /js
  static_dir: js
  secure: always
  
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  
- url: /([^/]*)
  static_files: \1.html
  upload: (.*).html
  secure: always

- url: /detail/([^/]*)
  static_files: detail.html
  upload: detail.html
  secure: always

- url: .*
  script: main.app
  secure: always


libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest